# TOOLCUBE
messages:
  pluginPrefix: "§7[§6§lСУНДУК-МАГИСТРА§7]"
  chestUpdateNotification: "§eЛут графа обновится через %time% минут!"
  chestOpenNotification: "§aСундук графа открыт!"
hologramname: "§e§lС§6§lУНДУК §e§lГ§6§lРАФА"
hologramsub: "§fЛут §6обновиться§а через " #минут
chestLocation:
  world: "spawn"
  x: -19
  y: 114
  z: -83
chestUpdateInterval: 30 # Интервал обновления сундука в минутах
# Настройки предметов
items:
  item_1:
    material: DIAMOND_SWORD
    name: "§6§lМеч Графа"
    lore:
      - "§7Меч легендарного графа"
    enchants:
      DAMAGE_ALL: 5
      DURABILITY: 3
    chance: 50
    amount: 1 # Количество предметов
  item_2:
    material: EXP_BOTTLE
    chance: 50
    amount: 54
  item_3:
    material: DIAMOND
    chance: 50
    amount: 64
  item_4:
    material: DIAMOND_HELMET
    name: "§6§lШлем графа"
    enchants:
      PROTECTION_ENVIRONMENTAL: 5
      DURABILITY: 3
      WATER_WORKER: 1
    chance: 50
    amount: 1
  item_5:
    material: DIAMOND_CHESPLATE
    name: "§6§lНагрудник графа"
    enchants:
      PROTECTION_ENVIRONMENTAL: 5
      DURABILITY: 3
    chance: 50
    amount: 1
  item_6:
    material: DIAMOND_LEGGINGS
    name: "§6§lПоножи графа"
    enchants:
      PROTECTION_ENVIRONMENTAL: 5
      DURABILITY: 3
    chance: 50
    amount: 1
  item_7:
    material: DIAMOND_BOOTS
    name: "§6§lБотинки графа"
    enchants:
      PROTECTION_ENVIRONMENTAL: 5
      DURABILITY: 3
    chance: 50
    amount: 1
  item_8:
    material: TOTEM
    name: "§6§lТотем графа"
    chance: 50
    amount: 1
  item_9:
    material: POTION
    potion_type: STRENGTH
    potion_level: 3
    chance: 50
    amount: 1
  item_10:
    material: POTION
    potion_type: SPEED
    potion_level: 3
    chance: 50
    amount: 1
  item_11:
    material: ARROW
    tipped: true
    potion_type: SLOW_FALLING
    chance: 50
    amount: 16
  item_12:
    material: EXP_BOTTLE
    chance: 50
    amount: 12
  item_13:
    material: WEB
    chance: 50
    amount: 10
  item_14:
    material: DIAMOND_AXE
    name: "§6§lСекира графа"
    enchants:
      DAMAGE_ALL: 6
      DURABILITY: 3
    chance: 30
    amount: 1 # Количество предметов
  item_15:
    material: TOTEM
    name: "§e§lЗолотой тотем"
    lore:
      - "§7Очень дорого стоит на аукционе"
    chance: 1
    amount: 1
  item_16:
    material: POTION
    potion_type: STRENGTH
    potion_level: 3
    chance: 50
    amount: 1
  item_17:
    material: POTION
    potion_type: SPEED
    potion_level: 3
    chance: 50
    amount: 1
  item_18:
    material: BOW
    name: "§6§lЛук Графа"
    enchants:
      ARROW_INFINITE: 1
      ARROW_FIRE: 1
      ARROW_KNOCKBACK: 3
      MENDING: 1
      ARROW_DAMAGE: 10
      DURABILITY: 3
    chance: 20
    amount: 1 # Количество предметов
  item_19:
    material: DIAMOND_HELMET
    name: "§e§lШлем графа"
    enchants:
      PROTECTION_ENVIRONMENTAL: 4
      DURABILITY: 3
      WATER_WORKER: 1
    chance: 50
    amount: 1
  item_20:
    material: DIAMOND_CHESPLATE
    name: "§e§lНагрудник графа"
    enchants:
      PROTECTION_ENVIRONMENTAL: 4
      DURABILITY: 3
    chance: 50
    amount: 1
  item_21:
    material: DIAMOND_LEGGINGS
    name: "§e§lПоножи графа"
    enchants:
      PROTECTION_ENVIRONMENTAL: 4
      DURABILITY: 3
    chance: 50
    amount: 1
  item_22:
    material: DIAMOND_BOOTS
    name: "§6§lБотинки графа"
    enchants:
      PROTECTION_ENVIRONMENTAL: 4
      DURABILITY: 3
    chance: 50
    amount: 1
  item_23:
    material: PAPER
    chance: 50
    amount: 12
  item_24:
    material: PAPER
    chance: 50
    amount: 12
  item_25:
    material: OBSIDIAN
    chance: 50
    amount: 16
  item_26:
    material: SUGAR_CANE
    chance: 50
    amount: 32
  item_27:
    material: GOLD_INGOT
    chance: 50
    amount: 32
  item_28:
    material: POTION
    potion_type: INVISIBILITY
    potion_level: 1
    chance: 100
    amount: 1
